{% set name = "morphospaces" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/morphospaces-{{ version }}.tar.gz
  sha256: a7c2dc4e53cb904900517aaa6f6944517f2fdbd36413d2562e5fe03faefd9038

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - h5py
    - magicgui
    - numpy
    - python >=3.8
    - pytorch-lightning
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - morphospaces
  commands:
    - pip list
    # - pip check  # pytorch-lightning requirements missmatch 
  requires:
    - napari
    - pip

about:
  home: https://github.com/morphometrics/morphospaces
  summary: a library for creating  and exploring morphospaces.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
